# Site settings
title: mz-fuzzy blog
email: mzfuzzy800@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  mz-fuzzy's blog about microcontrollers, arduino, internet of things, software development, linux etc...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mz-fuzzy.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  mz-fuzzy

# Build settings
markdown: kramdown
kramdown:
  input: GFM
